language: node_js
dist: precise
os: linux
group: stable
sudo: required
dist: trusty
env:
  - CXX=g++-6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
    - libxi-dev
node_js:
  - 6.9.1
before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
  - ulimit -c unlimited -S       # enable core dumps
script:
  - npm run lint
  - npm run cover
after_success:
  - cat coverage/lcov.info | coveralls
