matrix:
  include:
    - language: node_js
      dist: precise
      os: linux
      group: stable
      sudo: required
      dist: trusty
      env:
        - CXX=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - mesa-utils
          - xvfb
          - libgl1-mesa-dri
          - libglapi-mesa
          - libosmesa6
          - libxi-dev
      install:
        - yarn bootstrap
      node_js:
        - 10.16.0
      before_script:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
        - ulimit -c unlimited -S       # enable core dumps
      script:
        - npm run test ci
      after_success:
        - cat coverage/lcov.info | coveralls

    - language: python
      dist: precise
      os: linux
      group: stable
      sudo: required
      dist: trusty
      env:
        - CXX=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - mesa-utils
          - xvfb
          - libgl1-mesa-dri
          - libglapi-mesa
          - libosmesa6
          - libxi-dev
      before_install:
        - cd bindings/python/pydeck
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
      python:
        - "3.5"
        - "2.7"
      cache:
        pip: true
        directories:
          - ~/.npm  # NPM cache
      install:
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
        - pip install -e . --install-option "--build_all"
      script: pytest --cov=pydeck
