# Site settings
title: Deck.gl Blog
description: "A blog for deck.gl: WebGL-powered data visualization"
url: "http://deck.gl"
author:
  name: "Uber"
  url: "http://uber.github.io"

# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
sass:
  style: compressed
source: .
exclude: [./blog, README.md, Gemfile, Gemfile.lock]
destination: ./blog
permalink: /:year/:title

# Paginate settings
paginate: 8
paginate_path: /page:num/

# Tag page settings
tag_page_layout: tag
tag_page_dir: tag

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-feed
  