name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

permissions:
  contents: read

jobs:
  test-node:
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read

    steps:
      - uses: actions/checkout@86f86b36ef15e6570752e7175f451a512eac206b # v2.1.1

      - name: Use Node.js
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          # headless GL 6.0.1 needs recent version of Node 16.
          node-version: '16.19'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-utils xvfb libgl1-mesa-dri libglapi-mesa libosmesa6 libxi-dev
          yarn bootstrap

      - name: Run tests
        run: |
          xvfb-run -s "-ac -screen 0 1280x1024x16" yarn test ci

      - name: Coveralls
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # v1.2.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  test-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.1/install.sh | bash
          nvm install 16.9 && nvm use 16.9
          cd bindings/pydeck
          make setup-env
          make init
          cd ../pydeck-carto
          make init

      - name: Run pydeck tests
        run: |
          cd bindings/pydeck
          make ci

      - name: Run pydeck-carto tests
        run: |
          cd bindings/pydeck-carto
          make ci
